### ISSUE TITLE
[Bug]: ユーザー名が`/`となる

### ISSUE THREAD

**Issue by naruse666** [R1013-T/slide-share#1]
### 概要
GitHub OAuthからのユーザー登録でユーザー名が`/`となった。
プロフィール設定もできない。
権限が付与されれば設定可能になるもの？

### 対象パス
`/speakers`

**Comment by ryu1013-job** [comment]
@naruse666 
確認したところ、表示名が未設定です。再度 ログインすれば設定画面が開くと思います。

**Comment by naruse666** [comment]
再ログインで設定できました！
`/`は学校名と専攻の区切りでした 🙃
